spring.application.name=SpringRestfulServices-2-rest
logging.level.org.springframework.boot=INFO
# sbi URI Versioning
#spring.mvc.apiversion.use.path-segment=0
# sbi Request Parameter Versioning
#spring.mvc.apiversion.use.query-parameter=version
# sbi Request Header Versioning
#spring.mvc.apiversion.use.header=X-API-VERSION
# sbi Accept Header Versioning - Accept:application/json;version=1
#spring.mvc.apiversion.use.media-type-parameter[application/json]=version
# actuator
management.endpoints.web.exposure.include=*
# h2 config
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.profiles.active=local
# create an application-local file and put custom credentials for spring security
