spring.application.name=SpringRestfulServices-2-rest
logging.level.org.springframework.boot=INFO
# sbi URI Versioning
#spring.mvc.apiversion.use.path-segment=0
# sbi Request Parameter Versioning
#spring.mvc.apiversion.use.query-parameter=version
# sbi Request Header Versioning
spring.mvc.apiversion.use.header=X-API-VERSION
